### ISSUE TITLE
Add Github and Bioconductor parameters on create dockerfile function

### ISSUE THREAD

**Issue by brnleehng** [o2r-project/containerit#122]
Hi,

Is it possible for us to add github and bioconductor parameters to dockerfile? This would allow us to have a complete Dockerfile. 

``` R
dockerfile(from = utils::sessionInfo(),
  image = getImageForVersion(getRVersionTag(from)),
  maintainer = Sys.info()[["user"]], save_image = FALSE,
  env = list(generator = paste("containerit",
  utils::packageVersion("containerit"))), soft = FALSE, offline = FALSE,
  copy = NA, container_workdir = "/payload/", cmd = Cmd("R"),
  entrypoint = NULL, add_self = FALSE, vanilla = TRUE, silent = FALSE,
  predetect = TRUE, versioned_libs = FALSE, versioned_packages = FALSE,
  filter_baseimage_pkgs = FALSE,  github_packages = c(), bioconductor_packages = c())
```

Thanks,
Brian

**Comment by brnleehng** [comment]
+ @nuest

**Comment by nuest** [comment]
Thanks for pinging, I was on vacation...

In my words, you ask for manually adding packages from github or bioconductor. The thing is, you cannot even do that with CRAN packages currently. So for consistency, a `cran_packages = c()` parameter would be needed.

_Can you elaborate on your use case?_

`containerit` currently focusses on "magically" determining where to install packages from based on what is provided in the `from` parameter (see [code](https://github.com/o2r-project/containerit/blob/master/R/dockerfile.R#L298) and #101).

**Comment by nuest** [comment]
Thanks for pinging, I was on vacation...

In my words, you ask for manually adding packages from github or bioconductor. The thing is, you cannot even do that with CRAN packages currently. So for consistency, a `cran_packages = c()` parameter would be needed.

_Can you elaborate on your use case?_

`containerit` currently focusses on "magically" determining where to install packages from based on what is provided in the `from` parameter (see [code](https://github.com/o2r-project/containerit/blob/master/R/dockerfile.R#L298) and #101).

**Comment by nuest** [comment]
Bioconductor is supported in the `dev` branch: https://github.com/nuest/containerit/blob/dev/vignettes/bioconductor.Rmd
