### ISSUE TITLE
Closure Error on Dockerfile Creation

### ISSUE THREAD

**Issue by mischa2002k2** [o2r-project/containerit#126]
Hi,

I'm not sure if this is an issue with your package, but I can't create a dockerfile because of an unclear error message. To me its not clear at which point this results and I can't trace the error down.

Detailed issue description and code is found here: https://stackoverflow.com/questions/50813580/r-dockerfile-with-containerit-results-in-closure-error

Short description:
I run the dockerfile() function. This will try to run my testScript.r and result in the error "Object of type 'closure' can not be subsetted".
Though I do not encounter this error when I try to run my script within my session. 

This is the actual message:
```
INFO [2018-06-12 09:44:10] The supplied file testScript.r has no known extension. ContaineRit will handle it as an R script for packaging.
Fehler in session$otherPkgs : 
  Objekt des Typs 'closure' ist nicht indizierbar
```

**Comment by nuest** [comment]
Welcome to re-check this if you can provide a reproducible example.
