### ISSUE TITLE
Incompatible with the Windows file system

### ISSUE THREAD

**Issue by stephlocke** [o2r-project/containerit#129]
I've narrowed this down to the system2 call (I think!) wherein shQuote() gets applied to the R call but they never apply it to the arguments 🙄
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16127

Unfortunately, when we work with Windows directories it resolves things to a FQ UNC path so unless we had the option to provide our own working dir, the only other option I see for making this work for windows is to handle this quote issue, possibly with a system specific conditional prep step, or making all -e statements part of a script that gets Rscripted instead. 

```
args<-containerit:::.exprToParam(
    containerit:::.writeSessionInfoExp(tempfile())
)
system2("R", args = args)
> info <- sessionInfo()
> save(list = info, file = C:\\Users\\steph\\AppData\\Local\\Temp\\RtmpSEWwYi\\file1fe071106a0f)
    Error: unexpected input in "save(list = info, file = C:\"
    Execution halted
```

**Comment by stephlocke** [comment]
Perhaps processx could help https://www.tidyverse.org/articles/2018/09/processx-3.2.0/

**Comment by nuest** [comment]
Hi @stephlocke Thanks for pointing this out. I have a Windows system at hand now and will take a look.

**Comment by nuest** [comment]
@stephlocke closing this, because revisiting this now, I don't really know what commands you're actually running. Apologies for the silence! I hope you're still open to try out the current `dev` version to see if it works now. _Feel free to re-open with a minimal reprex._
