### ISSUE TITLE
Generate first Dockerfile

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#17]
What will be the CMD or ENTRYPOINT?
- [x] generate file
- [x] write test

Maybe a [helper script](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)

**Comment by MatthiasHinz** [comment]
Found a bug in R-ver (Rocker) https://github.com/rocker-org/rocker-versioned/issues/12

**Comment by MatthiasHinz** [comment]
By default, the Rocker-images already contain CMD ["R"] as a statement (if working correctly). Alternatively, we could also specify R as entrypoint.
