### ISSUE TITLE
Add graphical user interface for RStudio for packaging

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#27]
RStudio has some nice ways to create a GUI (when package is used in RStudio presumably), so when needing user input this could be handy

See RStudio Add-inns: https://rstudio.github.io/rstudioaddins/

**Comment by smwindecker** [comment]
Hi @nuest - a group of us at ropensci oz unconference 2018 are going start hacking at a few issues on containerit, including this one! Our fork and issue branch is here: https://github.com/ropenscilabs/containerit/tree/Issue27_GUI. Let us know if you have any thoughts on this one.

**Comment by nuest** [comment]
Thakns @smwindecker ! That's great! Apologies for not getting back to you sooner. I will take a look soon. I guess https://github.com/o2r-project/containerit/compare/master...ropenscilabs:master replaces #134 ?

**Comment by egouldo** [comment]
Thanks for alerting me to this @smwindecker. That's correct, @nuest!

**Comment by nuest** [comment]
Investigating https://github.com/o2r-project/containerit/pull/146/files now.

**Comment by nuest** [comment]
@egouldo Thank you so much for your awesome contribution, and my sincere apologies it took me that long to get around and take a look. As you might see in the history, I didn't do any development on this package for quite a while, but now I'm pushing some things forward, including your UI!

I don't know how to repay your efforts, but do let me know if you have an idea. What I can do is give some feedback on your code @clairemiller (can't tag Mark :frowning_face: )

During my review of the code, I made some style changes and wording changes, and refactoring, see https://github.com/nuest/containerit/commit/5d540923a279a49aef0d29ab31db2ea5a81fd81e

  - I am not an experiences Shiny/Addin developer, so for easier understandability (thinking about future me) I used explicit labels for the functions
  - Capitalising `Dockerfile`
  - Spaces around `=`, space after `,` in function argument list, use `<-` for object assignments and `=` for argument assignments
  - use the same type of quote character (not mixing `"` and `'`)
  - added a file `common.R` to have one share place to reduce duplication of code statements, e.g. the `volumes <- ` definition for file opening dialogs.
  - some aligning of function names (e.g. in `addin.R`)
  - use `basename` to get directory name instead of regex
  - Put `shiny::stopApp()` at the same spot in all event functions
  - rename script files

I created an issue to develop the UI further: https://github.com/o2r-project/containerit/issues/147  _Let me know what you think!_

Again: :+1: :100: :heart: Thank you! :rocket: 

![image](https://user-images.githubusercontent.com/1325054/61534429-e1345980-aa2f-11e9-8f5d-e6f67e5d7dde.png)

**Comment by nuest** [comment]
@egouldo @clairemiller please check if I got your ORCIDs right in the `DESCRIPTION` file: https://github.com/o2r-project/containerit/blob/dev/DESCRIPTION
