### ISSUE TITLE
Add RMarkdown Vignette

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#3]
https://cran.r-project.org/web/packages/datapack/vignettes/datapack-overview.html seems to have a good working process

- [x] initial vignette works as part of regular R package `build` ("setup works")
- [x] push modifications after review

**Comment by MatthiasHinz** [comment]
Initial build failed because of missing unknown pipe-operator.
Solution: added magrittr to package imports and to the initial vignette

**Comment by MatthiasHinz** [comment]
Second build failed because of the missing method, docker_build. 

"Fehler: Verarbeitung der Vignette 'basic.Rmd' mit folgender Diagnose fehlgeschlagen:
konnte Funktion "docker_build" nicht finden"

The method is not implemented in harbor (yet). We could either implement the method ourself or use googleComputeEngineR as a dependency, where it is implemented.

---> For now, I added googleComputeEngineR under suggestions

**Comment by MatthiasHinz** [comment]
Code part from the vignette doesn't look logical to me. Docker_build is building an image from a Dockerfile and expects a path to the dockerfolder and a name of the new image. 'container' seems to be misleading as a name here.

What kind of object shall method 'dockerfile' return? Easiest would be the path to the Dockerfile.

``` R
container <- dockerfile(sessionInfo(), ls())
docker_build(container) %>% docker_run(localhost)
image <- docker_build(container)
```

**Comment by nuest** [comment]
In the case you mentioned I expected `dockerfile(..)` to return an R object resembling a `Dockerfile`, so you could also do something like `write(x = dockerfile(sessionInfo()), file = "./Dockerfile")`.

`dockerfile(..)` could take a path as an argument (default `Dockerfile`) though.

**Comment by MatthiasHinz** [comment]
Basic vignette builds now locally, provided that the pipeline commented out:

```
#docker_build(container) %>% docker_run(localhost)
#image <- docker_build(container)
#con <- docker_run(image)
```
edited checklist

**Comment by nuest** [comment]
The vignette works, ist just must be updated when new features are complete.
