### ISSUE TITLE
Create labels

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#42]
Following the suggestions in [Label Schema](http://label-schema.org/rc1/) we can add some meta-information to the images

- [x] metadata labels (generated when, by who, ..)
- [x] arbitrary content (just create labels from a named list)
- [x] put session info output into a label as plain text
- [x] util function to read the labels from an image/container

**Comment by MatthiasHinz** [comment]
How to create and add labels of arbitrary content:
``` R
> library(containeRit)
> label1 <- Label(key1 = "this", key2 = "that", otherKey = "content")
> label2 <- Label(key1 = "this", key2 = "that", othekey = "content", multi_line = TRUE)
> df <- dockerfile(clean_session())
INFO [2017-03-16 15:26:45] Creating an R session with the following arguments:
	 R  --silent --vanilla -e "info <- sessionInfo()" -e "save(list = \"info\", file = \"/tmp/Rtmpl1oynQ/rdata-sessioninfof045502b59b\")"
> info <- sessionInfo()
> save(list = "info", file = "/tmp/Rtmpl1oynQ/rdata-sessioninfof045502b59b")
> 
> 
INFO [2017-03-16 15:26:46] Created Dockerfile-Object based on sessionInfo
> addInstruction(df) <- list(label1, label2)
> cat(format(df),sep = "\n")
FROM rocker/r-ver:3.3.2
MAINTAINER "matthiashinz"
WORKDIR /payload/
LABEL key1="this" key2="that" otherKey="content"
LABEL key1="this" \
	key2="that" \
	othekey="content"
CMD ["R"]
```

**Comment by MatthiasHinz** [comment]
Actually, we should mind certain restrictions / recommendations:

- Values with identical keys are overwriting each other. (see https://docs.docker.com/engine/reference/builder/#label) Hence, in order to have 'clean' Dockerfiles, we should make sure that their are no duplicate keys or at least print a warning, if this is the case.
- The Dockerfile reference recommends combining all labels to one single instruction, because otherwise each Label creates one layer which results in an inefficient image. Therefore we could
    1. Extend the addInstruction method with an argument `concatenate_labels = TRUE `that combines (a) given label(s) with the last occurring Label-instruction.
    2. Create a another method which does this job and maybe 'optimizes' the whole Dockerfile (name?)
    3. Other suggestions?
- When using the Label Schema, the label `org.label-schema.version` should occur. I would suggest to insert this label automatically if not present, as soon as the user applies one of those labels.
- Should we put labels in a certain position? At the moment, the generated Dockerfile follow this structure:
    1. FROM
    2. MAINTAINER
    3. RUN (install system dependencies, if necessary)
    4. RUN (install R packages, if necessary)
    5. WORKDIR
    6. COPY (copy scripts, resources, workspace images to working directory)
    7. CMD (start R session / batch execution of a script / rendering of a markdown file)

--> Maybe it is a good idea to manage label-instruction in a separate slot called 'metadata' and insert them as one single, multi-line instruction after the MAINTAINER-instruction? What do you think?

@edzer @MarkusKonk

**Comment by edzer** [comment]
Matthias, where does `clean_session()` come from? Also, Label() breaks:
```r
> label1 <- Label(key1 = "this", key2 = "that", otherKey = "content")
Error in Label(key1 = "this", key2 = "that", otherKey = "content") : 
  Constructor not yet implemented for this class.
```
I installed `containerit` from your fork.

**Comment by MatthiasHinz** [comment]
Sorry, that was my fault. I did not commit my recent changes yet. Now it should work.

`clean_session() `is a wrapper around the internal method [obtain_localSessionInfo](https://github.com/MatthiasHinz/containerit/blob/master/R/sessionInfo-localbuild-methods.R#L148). It basically invokes ` system2("R", args)` with the arguments and expressions printed out. The sessionInfo is saved to a temporary file and then read into the current session.

I use this whenever I need to avoid unnecessary dependencies, for instance, from containeRit package itself or anything attached to the current session by 'coincidence'. When I package R scripts or markdown files, they are always executed in such matter for the same reason.

**Comment by MatthiasHinz** [comment]
util function to read the labels from an image/container:

```
> docker_inspect(name="rocker/r-ver:3.3.2")
$Id
[1] "sha256:57cdcbf8e6b4673e8db4bcb0bb2162fde0efb60fe402946d86df5e906ff338ae"

$RepoTags
[1] "rocker/r-ver:3.3.2"

$RepoDigests
[1] "rocker/r-ver@sha256:60ece4a8388ee54a1f06f3f37d49d204363539d3e04e761613a39ccc0146b8ae"

$Parent
[1] ""

$Comment
[1] ""

[...]
```

**Comment by MatthiasHinz** [comment]
Put session info output into a label as plain text:

``` R
library(containeRit)
session <- clean_session()
df <- dockerfile(session)
addInstruction(df) <- Label_SessionInfo(session)
write(df)
```

Results to the Dockerfile:
```
FROM rocker/r-ver:3.3.2
MAINTAINER "matthiashinz"
WORKDIR /payload/
LABEL R_session_info="R version 3.3.2 (2016-10-31)\nPlatform: x86_64-pc-linux-gnu (64-bit)\nRunning under: Ubuntu 16.04.2 LTS\n\nlocale:\n [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8   \n [6] LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       \n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     "
CMD ["R"]
```


Modifying the penultimate command to 
`addInstruction(df) <- Label_SessionInfo(session, as_json = TRUE)`

results in
```
FROM rocker/r-ver:3.3.2
MAINTAINER "matthiashinz"
WORKDIR /payload/
LABEL R_session_info="{\"R.version\":{\"platform\":\"x86_64-pc-linux-gnu\",\"arch\":\"x86_64\",\"os\":\"linux-gnu\",\"system\":\"x86_64, linux-gnu\",\"status\":\"\",\"major\":\"3\",\"minor\":\"3.2\",\"year\":\"2016\",\"month\":\"10\",\"day\":\"31\",\"svn rev\":\"71607\",\"language\":\"R\",\"version.string\":\"R version 3.3.2 (2016-10-31)\",\"nickname\":\"Sincere Pumpkin Patch\"},\"platform\":\"x86_64-pc-linux-gnu (64-bit)\",\"locale\":\"LC_CTYPE=de_DE.UTF-8;LC_NUMERIC=C;LC_TIME=de_DE.UTF-8;LC_COLLATE=de_DE.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=de_DE.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=C\",\"running\":\"Ubuntu 16.04.2 LTS\",\"basePkgs\":[\"stats\",\"graphics\",\"grDevices\",\"utils\",\"datasets\",\"methods\",\"base\"]}"
CMD ["R"]
```

I think it's not so handy printing the session information in one line, but there such thing as a 'multiline-value', to my knowledge. Note that this is only a minimal example. When packages a loaded, the session info is even larger, especially in for the json form. The json-form equals to the session info object and contains more detailed metadata, while the 'normal' label equals to the printed form and only includes the most relevant information.

**Comment by MatthiasHinz** [comment]
The 'maintainer' instruction is deprecated according to the latest spec. They recommend replacing it by labels. We should consider that!

https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

**Comment by MatthiasHinz** [comment]
Metadata according to the Label Schema can now be created as follows:

``` R
df <- dockerfile(clean_session())
factory <- LabelSchemaFactory()
label <- factory(name = "ImageName", description = "Description of the image", build_date = Sys.time())
addInstruction(df) <- label
write(df)
```
That creates a Dockerfile similar to the following:

```
FROM rocker/r-ver:3.3.2
MAINTAINER "matthiashinz"
WORKDIR /payload/
LABEL org.label-schema.schema-version="1.0.0-rc.1" \
	org.label-schema.build-date="2017-03-21T18:08:29+0100" \
	org.label-schema.name="ImageName" \
	org.label-schema.description="Description of the image"
CMD ["R"]
```

**Comment by nuest** [comment]
Regarding `MAINTAINER`, shouldn't the default use the label and using the deprecated element require user interaction?

**Comment by nuest** [comment]
What about if I want to use my own namespace?

```r
label <- factory("info.o2r.name" = "myProject_ImageName")
```

**Comment by MatthiasHinz** [comment]
You mean to use `info.o2r.name` instead of `org.label-schema.` with the label schema? Sure, I could add a 'namespace' argument to the `LabelSchemaFactory`, with default `org.label-schema.`. Would take me 5 minutes to implement this.

**Comment by nuest** [comment]
It should be possible to use own namespaces, not with a namespace argument but simply by not processing the names of the list:

```r
label <- factory("info.o2r.name" = "myProject_ImageName", "org.labe-schema.name="ImageName", "yet.another_labelname"="true")
```

I guess you could introduce a more generic `LabelFactory` to handle that, and make a specific `NamespacedLabelFactory` that is used by `LabelSchemaFactory`, or something like that?

**Comment by MatthiasHinz** [comment]
You can just use the generic Label-constructor for this (see my first comment in this thread). The usage is `Label(..., multi_line = FALSE)`, while `...` can virtually any amount of arguments and `multi_line `influences formatting (the whole label one line or one line per key / value pair)

So you can write 
`label <- Label("info.o2r.name" = "myProject_ImageName", "org.label-schema.name="ImageName", "yet.another_labelname"="true")`

The reason why I introduced the factory, is to give a certain degree of content assist and validation. The factory - method expects exactly those 22 arguments specified by the schema as "Label", while each of them is optional. Also, I made sure that the schema-version label (an argument with default value)  is part of the result, which is the only mandatory item according to the spec. The keys are read from a text file that could easily be replaced/modified when there is a new spec.

**Comment by nuest** [comment]
Ok - I see. Please re-check the examples in the documentation so that they contain attributes with and without a "namespaced name", just so that future users are not confused. Thanks for the clarification!

**Comment by MatthiasHinz** [comment]
I added this example:
```
# A simple label that occupies one line:
label1 <- Label(key1 = "this", key2 = "that", otherKey = "content")
# A multiline label with one key/value pair per line
label2 <- Label("info.o2r.name" = "myProject_ImageName", "org.label-schema.name"="ImageName", "yet.another_labelname"="true", multi_line = TRUE)
#label with fixed namespace for all keys
label3 <- Label("name"="A name", "description" = "A description", label_ns = "my.label.ns.")
df <- dockerfile(clean_session())
addInstruction(df) <- list(label1, label2, label3)
cat(format(df),sep = "\n")
```

Which results into:
```
FROM rocker/r-ver:3.3.3
LABEL maintainer="matthiashinz"
WORKDIR /payload/
LABEL key1="this" key2="that" otherKey="content"
LABEL info.o2r.name="myProject_ImageName" \
	org.label-schema.name="ImageName" \
	yet.another_labelname="true"
LABEL my.label.ns.name="A name" my.label.ns.description="A description"
CMD ["R"]
```
