### ISSUE TITLE
Evaluate CodeDepends package for determining libraries

### ISSUE THREAD

**Issue by MatthiasHinz** [o2r-project/containerit#53]
The package CodeDepends (see https://github.com/duncantl/CodeDepends) provides functions to analyze R scripts and code.

The function `scriptInfo` can determine, amongst others, 

> the names of any libraries explicitly loaded within this code

This could be a useful add-on for packaging R scripts.

**Comment by nuest** [comment]
Yes that sounds quite useful! Good find!

**Comment by nuest** [comment]
Check also packages mentioned in https://twitter.com/_ColinFay/status/975027894790520834

**Comment by nuest** [comment]
Better packages is `automagic`, see #101
