### ISSUE TITLE
Vignette is not installed!

### ISSUE THREAD

**Issue by MatthiasHinz** [o2r-project/containerit#54]
I noticed that the `.gitignore` file includes the directory `inst/doc`, where normally the vignette should be located in *.html *.Rmd and *.pdf format. Hence, the command `vignette("basic")` fails after installing the package from GitHub because there is no vignette available.

I wonder if this is done by intention. If not, please remove the .gitignore entry!

**Comment by nuest** [comment]
Yes that is done by intention. git is for source code, not for rendered documentation. #57 is a more reasonable way if a users wants to read documentation without installing the package. Eventually, the package should end up on CRAN and that will solve this issue.
