### ISSUE TITLE
Package a session (basic)

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#6]
Create a small session (load few packages, including one from CRAN but not in base packages) and create a Dockerfile that is as close as possible to recreate that session.

Based on `sessionInfo()$running` we have a mapping from running string to base image. In our case all running strings map to rocker.

_Also check_ `devtools::session_info()`, could be useful to determine installation source.

Open questions:

- how can we fill the `MAINTAINER` field?

**Comment by nuest** [comment]
Could be useful to "save" the Dockerfile to a connection (allowing file, stream etc.), see discussion at https://github.com/hadley/xml2/pull/158

**Comment by MatthiasHinz** [comment]
**Workflow: Reproduce sessionInfo**

1. Analyze local sessionInfo:
	a) which base packages are attached?
	b) which other packages are attached? (and need to be installed?)
	c) which other packages are loaded via namespace and not attached? (and need to be installed?)
2. For the non-base packages (1b and 1c), determine system dependencies (use sysreq-package or shiny dependencies)
	--> RUN apt-get update (evtl. mit quiet parameter -qq)
	--> create RUN command(s) that install system dependencies with apt-get
3. For the non-base packages (1b and 1c), determine how to install them in R
	- if pkg$repository IS CRAN --> use install.packages("..")
	- if pkg$RemoteType IS GitHub --> use devtools::install GitHub (devtools::session_info() can also be used for this, but the required information seems to be available in normal sessionInfo() as well.) 
	- consider using remotes-package if useful https://github.com/r-pkgs/remotes
	- [...]
	--> create RUN command(s) with Rscript -e
4. Start R with preloaded and attach libraries according to sessionInfo
	- This seems to be rather tricky since R -e <expr> and R -f <file> will alsways terminate after batch execution (also does not work with the --interactive flag). The only way to restore an interactive session with required libraries seems to be defining a Rprofile.site file and setting R_PROFILE environment variable to its location
	- The R_PROFILE file must contain a .First-function which
	    - attaches required packages using require(...) (or library)?
	    - load namespaces via requireNameSpace()

**Further functionality:**
I. A package test creates a local R session and a dockerized R session and compares both sessionInfo objects (package names, package versions(?), R versions, locales(?), platform(??) ... others)
II. Containerit may perform test-builds and check if all necessary packages are correctly installed can be loaded (maybe later)

**Comment by nuest** [comment]
**Regarding `3.`**:
- Instead of `install.packages(..)` we can utilize `littler`.
The way to install packages should depend on the used base image. If we use an `rocker/r-ver` (or descendants `verse`, `tidyverse` etc.) base image, then [use littler](https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile#L38). If we use another base image (e.g. `debian`, then stop with and error message that this base image is not supported.
- CRAN-mirror: that should already be [configured in the base image](https://github.com/rocker-org/rocker-versioned/blob/f940dba482954b458100dc3cc2018c8952a51d2f/r-ver/3.1.0/Dockerfile#L96). In case somebody uses another base image, we should have a utitlity method `add_cran_mirror("mirror url")` (better names welcome) that creates the required RUN command.

**Regarding `4.`**: That is not necessary at the moment, but is a nice idea - moved it to #37. The script that actually does something in the container must load the packages. For your testing, please add a simple R script that `library`-loads the packages.

Regarding "Further I.": Do check package names and versions, check R version, check locale. Do not compare platform or other things as of now.

Regarding "Further II.": if you think of useful future tasks, please add an issue.
