### ISSUE TITLE
Incorrect script folder uploaded - cutoff filename?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [o2r-project/containerit#76]
Hi, I'm trying to use `containeRit` to automatically schedule a script on a GCE instance.

I'm using this demo script that is passed like this:

```r
script <- system.file("schedulescripts", "schedule.R", package = "googleComputeEngineR")
# "/Users/mark/dev/R/libs/googleComputeEngineR/schedulescripts/schedule.R"
container <- dockerfile(script, 
                        save_image = TRUE, 
                        copy = "script_dir", 
                        cmd = CMD_Rscript(basename(script)))
write(container, file = "Dockerfile")
```

The Dockerfile is created, but it looks like the folder is shortened from `"/Users/mark/dev/R/libs/googleComputeEngineR/schedulescripts/"` to `"gineR/schedulescripts"`:

```
FROM rocker/r-ver:3.4.0
LABEL maintainer="mark"
RUN export DEBIAN_FRONTEND=noninteractive; apt-get -y update \
 && apt-get install -y libcurl4-openssl-dev \
	libssl-dev \
	make
RUN ["install2.r", "-r 'https://cloud.r-project.org'", "googleCloudStorageR", "googleAuthR", "Rcpp", "assertthat", "digest", "crayon", "withr", "mime", "R6", "jsonlite", "xtable", "magrittr", "httr", "curl", "testthat", "devtools", "readr", "hms", "shiny", "httpuv", "memoise", "htmltools", "openssl", "tibble", "remotes"]
RUN ["installGithub.r", "hadley/rlang@c351186"]
WORKDIR /payload/
COPY ["gineR/schedulescripts", "gineR/schedulescripts/"]
COPY ["./.RData", "./"]
CMD ["R", "--vanilla", "-f", "schedule.R"]
```

Is this a bug or something I'm doing?

**Comment by MarkEdmondson1234** [comment]
I sorted this out by coping the file into the working directory, but I guess more a work around than a fix. 

```r
script <- system.file("schedulescripts", "schedule.R", package = "googleComputeEngineR")

## put the "schedule.R" script in the working directory
file.copy(script, getwd())

## it will run the script whilst making the dockerfile
container <- dockerfile("schedule.R",
                        copy = "script_dir",
                        cmd = CMD_Rscript("schedule.R"))
write(container, file = "Dockerfile")
```

**Comment by nuest** [comment]
@MarkEdmondson1234 Thanks for trying this out, your issue slipped through my inbox - Sorry!

Good you found a workaround. I'll take a look at this, because the `script_dir` option should do just what you expect, as you pass a full path. Note to self: 

- [ ] investigate [here](https://github.com/o2r-project/containerit/blob/79652585cfcc56f85b7041c6d1275c92cddd9c3c/R/dockerfile.R#L332)
- [ ] add test

**Comment by nuest** [comment]
Closing this with functioning workaround. Supporting full paths is really hard, because we don't know where in the directory tree in the container to put that file...

**Comment by nuest** [comment]
Closing this with functioning workaround. Supporting full paths is really hard, because we don't know where in the directory tree in the container to put that file...
