### ISSUE TITLE
save_image looks for an often ignored file .RData

### ISSUE THREAD

**Issue by MarkEdmondson1234** [o2r-project/containerit#77]
When using the `save_image` flag the produced `Dockerfile` looks to add `.RData` to itself.  The thing is, this file is usually ignored for GitHub so when using build triggers it fails.  

```r
container <- dockerfile(script, save_image = TRUE, copy = "script_dir", cmd = CMD_Rscript(basename(script)))
```

It would be nice if instead of `TRUE`or `FALSE` you can specify a filename to save the `.RData` to, so you can rename it if necessary.

**Comment by nuest** [comment]
Just to get your goal: You would like to containerit to save the file under a different name, so that you can commit it to a GitHub repository?

Since `save_image` enables or disables the saving of the file during the packaging process, I'd like to understand more what your use case is before making this change. I wonder if both `TRUE` and `myname.Rdata` (the latter implying `TRUE`) are needed.

**Comment by MarkEdmondson1234** [comment]
Yes - I wanted to build an image of an entire RStudio project, that included `.RData` and couldn't add the `.RData` file to the GitHub repo as it was in `.gitignore`, and need to upload to GitHub to trigger a Docker build using Google build triggers.  

I could modify the `.gitignore` but thats usually a default template I don't touch and easily forgotten I think, so the suggestion is to be able to specify the filename of the `.RData` file in the function call.

**Comment by nuest** [comment]
Just to clarify: the `dockerfile(..)` function _calls_ `save.image()`. I updated the documentation to better describe the default behaviour.

I hope this is now more helpful for your use case:

```
> library("containerit")
> mydata <- c(1:10)
> more_data <- "test"
> the_dockerfile <- dockerfile(save_image = list("mydata", save_image_filename = "datafile.Rdata"))
INFO [2018-08-10 12:52:45] Going online? TRUE  ... to retrieve system dependencies (sysreq-api)
INFO [2018-08-10 12:52:45] Trying to determine system requirements for the package(s) 'rjson,magrittr,formatR,futile.logger,lambda.r,curl,Rcpp,futile.options,stringi,stringr,stevedore,semver,remotes' from sysreqs online DB
INFO [2018-08-10 12:52:47] Adding CRAN packages: curl, formatR, futile.logger, futile.options, lambda.r, magrittr, Rcpp, remotes, rjson, semver, stringi, stringr
INFO [2018-08-10 12:52:47] Adding GitHub packages: richfitz/stevedore@0f78d55db56d3d339dcafde698d20e77e0009626
INFO [2018-08-10 12:52:47] Created Dockerfile-Object based on sessionInfo
> list.files()
[1] "datafile.Rdata"
> rm(list = ls())
> ls()
character(0)
> load("datafile.Rdata")
> mydata
 [1]  1  2  3  4  5  6  7  8  9 10

```

**Comment by MarkEdmondson1234** [comment]
Thanks, I'll give it a go and reopen if needed.
