### ISSUE TITLE
Support other base images

### ISSUE THREAD

**Issue by MarkEdmondson1234** [o2r-project/containerit#78]
I have a working build, but it uses packages I have another docker image already compiled for.  I would like to build from that one to speed up build time.  

However when I try, I get the error:

```r
container <- dockerfile(script, copy = "script_dir", image = "gcr.io/gcer-public/googleauthr-verse", cmd = CMD_Rscript(basename(script)))
#Error in dockerfile(script, copy = "script_dir", image = gce_tag_container("googleauthr-verse",  : 
#  Invalid base image. Currently, only the following base images are supported: rocker/r-ver
#rocker/rstudio
#rocker/tidyverse
#rocker/verse
#rocker/geospatial
```

**Comment by nuest** [comment]
Thanks for giving containerit a proper check!

Would you be able to share the script file you use for testing, just to be sure I run into the same issues?

**Comment by nuest** [comment]
Looking into this a bit, we would also need to expose the platform to the user, up to the function `dockerfile()`.

For now, I made the validation stuff more defense, just using warnings, see commit above. To be contained in a PR soon.

```r
> container <- dockerfile(from = sessionInfo(), image = "gcr.io/gcer-public/googleauthr-verse")
Called from: eval(expr, p)
Browse[1]> n
debug at /home/daniel/git/o2r/containerit/R/dockerfile.R#237: .dockerfile <- .create_run_install(.dockerfile = .dockerfile, 
    pkgs = pkgs, platform = platform, soft = soft, versioned_libs = versioned_libs)
Browse[2]> c
INFO [2017-06-28 11:26:06] Trying to determine system requirements for the package(s) 'containeRit, futile.logger, lambda.r, futile.options' from sysreq online DB
INFO [2017-06-28 11:26:07] Adding CRAN packages: futile.logger, lambda.r, futile.options
INFO [2017-06-28 11:26:07] Created Dockerfile-Object based on sessionInfo
Warning messages:
1: In dockerfile(from = sessionInfo(), image = "gcr.io/gcer-public/googleauthr-verse") :
  Unsupported base image. Proceed at your own risk. The following base images are supported: rocker/r-ver
rocker/rstudio
rocker/tidyverse
rocker/verse
rocker/geospatial
2: In FUN(X[[i]], ...) :
  Failed to identify source for package containeRit. Therefore the package cannot be installed in the Docker image.

3: In .create_run_install(.dockerfile = .dockerfile, pkgs = pkgs, platform = platform,  :
  Platform could not be detected, proceed at own risk.
> print(container)
FROM gcr.io/gcer-public/googleauthr-verse
LABEL maintainer="daniel"
RUN ["install2.r", "-r 'https://cloud.r-project.org'", "futile.logger", "lambda.r", "futile.options"]
WORKDIR /payload/
CMD ["R"]
```

**Comment by nuest** [comment]
@MarkEdmondson1234 please try out the current master if that works out for you (for now).

**Comment by MarkEdmondson1234** [comment]
I tried it today and it still has error?

```r
devtools::install_github("nuest/containerit")
> containeRit::dockerfile("schedule.R", image = "trestletech/plumber")
Error in containeRit::dockerfile("schedule.R", image = "trestletech/plumber") : 
  Invalid base image. Currently, only the following base images are supported: rocker/r-ver
rocker/rstudio
rocker/tidyverse
rocker/verse
rocker/geospatial
``

**Comment by nuest** [comment]
I've found your blog post http://code.markedmondson.me/4-ways-schedule-r-scripts-on-google-cloud-platform/ ! Very cool! So I used that to follow your steps, though I don't get quite your results yet, probably because you're actually loading more packages.

(Side note: I potentially found a bug in `sysreqs` along the way, see https://github.com/r-hub/sysreqs/pull/4 - for now you'd have to use my branch `fallback-rver` there, or wait until the sysreqs online DB is updated...)

The problem here is that I must know the base platform of the used image, so I ended up restructuring some code and adding `trestletech/plumber` to the list of supported Debian images, because it is based on a rocker image. I've changed that, so now I get this:

```R
cmd <- Cmd(params = "schedule.R")
dockerfile <- dockerfile("schedule.R",
                         image = "trestletech/plumber",
                         copy = "script_dir", 
                         cmd = cmd,
                         soft = TRUE)

print(dockerfile)
```

creates

```
FROM trestletech/plumber
LABEL maintainer="daniel"
RUN export DEBIAN_FRONTEND=noninteractive; apt-get -y update \
 && apt-get install -y make
RUN ["install2.r", "-r 'https://cloud.r-project.org'", "readr", "googleCloudStorageR", "googleAuthR", "Rcpp", "digest", "crayon", "withr", "mime", "R6", "xtable", "magrittr", "httr", "rlang", "testthat", "devtools", "hms", "shiny", "httpuv", "memoise", "htmltools", "tibble"]
WORKDIR /payload/
COPY [".", "./"]
CMD ["schedule.R"]
```

Still missing:

- `EXPOSE` statement
- `Entrypoint`, see #89

I hope to get to that during this week.

Can you try again with my fork's master (https://github.com/nuest/containerit), increase the log level with `futile.logger::flog.threshold(futile.logger::DEBUG)` and let me know the output?

**Comment by MarkEdmondson1234** [comment]
Thanks a lot, like I say in the post this package is like magic, and will hopefully make working with Docker for folks a lot easier.  Now I've looked at `trestletech/plumber` it seems to only take base R image and install plumber, so I guess the same effect would be to just include `library(plumber)` in the scheduled script and use base R image.
