### ISSUE TITLE
Step 9/11 copy failed

### ISSUE THREAD

**Issue by pat-s** [o2r-project/containerit#94]
Hi Daniel,

first of all a huge thanks for that awesome package!

I created a dockerfile and face the following problem during `docker build`:

```
Step 8/11 : WORKDIR /payload/
 ---> eba9c781df13
Removing intermediate container ea218f9bf742
Step 9/11 : COPY some/path/01_data_preprocesing.Rmd some/path/01_data_preprocesing.Rmd
COPY failed: stat /var/lib/docker/tmp/docker-builder164447896/some/path/01_data_preprocesing.Rmd: no such file or directory
```

Any idea what could be the source of the problem? I'm using the latest Github version of `containerit`

**Comment by nuest** [comment]
Thanks for giving this a try. Can you let me know the actual call to `dockerfile(..)` and the result of `getwd()`, please?

It seems there is a problem with the working directory and where containerit is looking for the file.

**Comment by pat-s** [comment]
Will let you know ASAP, on vacation until next monday 👍

**Comment by nuest** [comment]
@pat-s feel free to re-open if this is still an issue.

**Comment by pat-s** [comment]
Hi Daniel,

yes sorry, I forgot about this issue. 
Its currently not important anymore and I'll see if it still applies next time.
