### ISSUE TITLE
SessionInfo could not be determined When running the script of packaging an R script

### ISSUE THREAD

**Issue by wtzhou74** [o2r-project/containerit#98]
Hi

I got the following errors:
```
Error in obtain_localSessionInfo(file = file, vanilla = vanilla, slave = silent,  : 
  Failed to execute the script locally! A sessionInfo could not be determined.
In addition: Warning message:
running command '"R" --silent --slave --vanilla -e "source(file = \"C:\\\\Users\\\\ZHOU WENTAO\\\\AppData\\\\Local\\\\Temp\\\\RtmpwFIhMR\\\\containerit_56683bf167b9.R\", echo = FALSE)" -e "info <- sessionInfo()" -e "save(list = \"info\", file = \"C:\\\\Users\\\\ZHOUWE~1\\\\AppData\\\\Local\\\\Temp\\\\RtmpwFIhMR\\\\rdata-sessioninfo56687c8820c4\")"' had status 1 
```
When I run the following codes from http://o2r.info/2017/05/30/containerit-package/ to package an R script:
```
# create simple script file
scriptfile <- tempfile(pattern = "containerit_", fileext = ".R")
writeLines(c('library(rgdal)',
             'nc <- rgdal::readOGR(system.file("shapes/", package="maptools"), "sids", verbose = FALSE)',
             'proj4string(nc) <- CRS("+proj=longlat + datum=NAD27")',
             'plot(nc)'), scriptfile)

# use a custom startup command
scriptCmd <- CMD_Rscript(basename(scriptfile))

# create Dockerfile for the script
dockerfile_object <- dockerfile(from = scriptfile, silent = TRUE, cmd = scriptCmd)

print(dockerfile_object)
```
May I ask what are the root causes which give rise to this problem.

Thanks,
Wentao

**Comment by nuest** [comment]
Can you please provide your `sessionInfo()` output, and the whole log - thanks!

**Comment by wtzhou74** [comment]
Hi @nuest Below are the sessionInfo
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] containerit_0.2.3

loaded via a namespace (and not attached):
 [1] digest_0.6.12        withr_2.1.0          R6_2.2.2             futile.options_1.0.0 git2r_0.19.0        
 [6] magrittr_1.5         httr_1.3.1           stringi_1.1.2        curl_3.0             futile.logger_1.4.3 
[11] devtools_1.13.4      lambda.r_1.2         rjson_0.2.15         tools_3.3.2          stringr_1.2.0 
```
The` containerit` was installed via `devtools::install_github("o2r-project/containerit")`. And I was wondering whether or not there are any other packages that I need to install?
The whole logs are:
```
> library("containerit")

Attaching package: ‘containerit’

The following object is masked from ‘package:base’:

    Arg

> scriptCmd <- CMD_Rscript(basename(scriptfile))
> dockerfile_object <- dockerfile(from = scriptfile, silent = TRUE, cmd = scriptCmd)
Error: unexpected input in "source(file = C:\"
Execution halted
Error in obtain_localSessionInfo(file = file, vanilla = vanilla, slave = silent,  : 
  Failed to execute the script locally! A sessionInfo could not be determined.
In addition: Warning message:
running command '"R" --silent --slave --vanilla -e "source(file = \"C:\\\\Users\\\\ZHOU WENTAO\\\\AppData\\\\Local\\\\Temp\\\\Rtmp4UQkIV\\\\containerit_313456b675e.R\", echo = FALSE)" -e "info <- sessionInfo()" -e "save(list = \"info\", file = \"C:\\\\Users\\\\ZHOUWE~1\\\\AppData\\\\Local\\\\Temp\\\\Rtmp4UQkIV\\\\rdata-sessioninfo31341fb689b\")"' had status 1 
```
Anything else you need?

Thanks,

**Comment by MatthiasHinz** [comment]
Hi everybody, 
I think that your problem is windows-related. Your script worked fine on my Linux machine but I got similar errors on windows. The root cause seems to be the command shown in the warning message, which is syntactically incorrect. Normally, it should be possible to execute this string in the terminal (as printed below). 

``` R
> cat('"R" --silent --slave --vanilla -e "source(file = \"C:\\\\Users\\\\ZHOU WENTAO\\\\AppData\\\\Local\\\\Temp\\\\Rtmp4UQkIV\\\\containerit_313456b675e.R\", echo = FALSE)" -e "info <- sessionInfo()" -e "save(list = \"info\", file = \"C:\\\\Users\\\\ZHOUWE~1\\\\AppData\\\\Local\\\\Temp\\\\Rtmp4UQkIV\\\\rdata-sessioninfo31341fb689b\")"')
"R" --silent --slave --vanilla -e "source(file = "C:\\Users\\ZHOU WENTAO\\AppData\\Local\\Temp\\Rtmp4UQkIV\\containerit_313456b675e.R", echo = FALSE)" -e "info <- sessionInfo()" -e "save(list = "info", file = "C:\\Users\\ZHOUWE~1\\AppData\\Local\\Temp\\Rtmp4UQkIV\\rdata-sessioninfo31341fb689b")"
```

The problem is that the inner quotation marks should be replaced by escape sequences or single quotation marks. I would say that the code beginning from the following line and below must be altered for windows-compatiblity. https://github.com/o2r-project/containerit/blob/79652585cfcc56f85b7041c6d1275c92cddd9c3c/R/sessionInfo-localbuild-methods.R#L60

---
Please note that under window you will also have to set the PATH environment variable accordingly so that it points to the R.exe file. Also, your dockerfile will not build or execute correctly unless you set your R working directory in a parent folder of your R-script (and other resources), which is then assumed to be the Docker build context as well.

Cheers!

**Comment by nuest** [comment]
@wtzhou74 feel free to re-open if this issue still exists.

**Comment by stephlocke** [comment]
I downloaded this yday on windows and I'm getting this issue where the quotes seem to disappear around file names in this source line

**Comment by stephlocke** [comment]
I've narrowed this down to the system2 call  (I think!) wherein `shQuote()` gets applied to the R call but they never apply it to the arguments 🙄 
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16127

Unfortunately, when we work with tempfiles it resolves things to a FQ UNC path so unless we had the option to provide our own working dir, the only other option I see for making this work for windows is to handle this quote issue, possibly with a system specific conditional prep step.

```
args<-containerit:::.exprToParam(
    containerit:::.writeSessionInfoExp(tempfile())
)
system2("R", args = args)
> info <- sessionInfo()
> save(list = info, file = C:\\Users\\steph\\AppData\\Local\\Temp\\RtmpSEWwYi\\file1fe071106a0f)
    Error: unexpected input in "save(list = info, file = C:\"
    Execution halted
```
